//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinSwitcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinSwitcher.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting WinSwitcher.
        /// </summary>
        public static string exitAnnouncement {
            get {
                return ResourceManager.GetString("exitAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No apps found.
        /// </summary>
        public static string noAppsFound {
            get {
                return ResourceManager.GetString("noAppsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No windows found.
        /// </summary>
        public static string noWindowsFound {
            get {
                return ResourceManager.GetString("noWindowsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open windows.
        /// </summary>
        public static string openWindows {
            get {
                return ResourceManager.GetString("openWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running apps.
        /// </summary>
        public static string runningApps {
            get {
                return ResourceManager.GetString("runningApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settingsButton {
            get {
                return ResourceManager.GetString("settingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinSwitcher started.
        /// </summary>
        public static string startAnnouncement {
            get {
                return ResourceManager.GetString("startAnnouncement", resourceCulture);
            }
        }
    }
}
